# Generated by Django 2.0 on 2018-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('transcripts', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
