# Generated by Django 2.0 on 2018-10-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='no_of_persons',
            field=models.IntegerField(default=2),
        ),
    ]
