# Generated by Django 2.0 on 2018-10-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_meeting_no_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
